In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
import numpy as np
from sklearn import metrics
from nltk import classify 
import sklearn.metrics as metrics

categories =[0, 1]

trainf = pd.read_csv("training_data (1).csv")
testf = pd.read_csv("test_data (1).csv")

X_train =trainf['SentimentText']
Y_train = trainf['Sentiment']
X_test = testf['SentimentText']
Y_test = testf['Sentiment']
SentimentText = trainf['SentimentText']
label = trainf['Sentiment']
trainf.dtypes

Unnamed: 0              int64
Unnamed: 0.1            int64
ItemID                  int64
Sentiment               int64
SentimentText          object
integer_conversion     object
split                 float64
dtype: object

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(3,5))
sns.countplot(x="Sentiment", data=trainf, palette="viridis")
plt.xlabel("Negative Tweets =0,                Positive tweets=1")
plt.ylabel("No of Tweets")
plt.show()

<Figure size 300x500 with 1 Axes>

##### Splitting the dataset
After preprocessing we divide the data in test and train set. The data we use is usually split into training data and test data. The training set contains a known output and the model learns on this data and the test dataset is to test our model’s prediction. We did this using SciKit-Learn library in Python using the train_test_split method. In this project we have divided the data in 75: 25 ratio. That is, the training size is 75% and testing size is 25% of the whole data.

In [14]:
# from sklearn.model_selection import train_test_split
# X_train,X_test,Y_train,Y_test = train_test_split(SentimentText, label, test_size=0.25, random_state=0) 

from sklearn.linear_model import LogisticRegression
Pipe_regression= Pipeline([('vect', CountVectorizer()),('Classifier', LogisticRegression())])
Pipe_regression.fit(X_train,Y_train)
pred = Pipe_regression.predict(X_test)
pred_LR = Pipe_regression.predict(X_train)
print(pred)

print('Accuracy of Logistic regression = %r' %np.mean(pred == Y_test) )
print('Confusion Matrix Logistic Regression')
print(metrics.confusion_matrix(Y_test, pred))
print("Logistic Regression Accuracy Score =", metrics.f1_score(Y_test, pred))

from nltk import NaiveBayesClassifier
Pipe_NaiveBayes = Pipeline([('vect', CountVectorizer()),('Classifier', MultinomialNB()),])
Pipe_NaiveBayes.fit(X_train,Y_train)
pred = Pipe_NaiveBayes.predict(X_test)
pred_NB = Pipe_NaiveBayes.predict(X_train)

print('Accuracy of Naive Bayes classifer = %r' % np.mean(pred == Y_test))
print('Confusion Matrix Naive Bayes model')
print(metrics.confusion_matrix(Y_test, pred))
print("Naive Bayes Classifier Accuracy Score =", metrics.f1_score(Y_test, pred))
print(pred)

from sklearn.linear_model import SGDClassifier
Pipe_SGD = Pipeline([('vect', CountVectorizer()),('Classifier', SGDClassifier())])
Pipe_SGD.fit(X_train, Y_train)
pred = Pipe_SGD.predict(X_test)
pred_SGD = Pipe_SGD.predict(X_train)

print('Accuracy Support Vector Machine = %r:' %np.mean(pred == Y_test))
print(' Confusion Matrix Support Vector Machine model')
print(metrics.confusion_matrix(Y_test, pred))
print("Support Vector Machine Accuracy Score =", metrics.f1_score(Y_test, pred))
print(pred)


table = pd.DataFrame({'Tweet':X_train,'Label':Y_train,'LR_Prediction':pred_LR,'NB_Prediction':pred_NB,'SGD_Prediction':pred_SGD})
writer = pd.ExcelWriter('Output.xlsx', engine='xlsxwriter')
table.to_excel(writer, sheet_name='Output')
writer.save()

print('Saved output to file.')

D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[0 0 0 ... 1 1 0]
Accuracy of Logistic regression = 0.7663724801925584
Confusion Matrix Logistic Regression
[[6029 2751]
 [1908 9254]]
Logistic Regression Accuracy Score = 0.7988949799283465
Accuracy of Naive Bayes classifer = 0.757797613077926
Confusion Matrix Naive Bayes model
[[6248 2532]
 [2298 8864]]
Naive Bayes Classifier Accuracy Score = 0.7858852735171558
[0 1 0 ... 1 1 1]
Accuracy Support Vector Machine = 0.7632133186240097:
 Confusion Matrix Support Vector Machine model
[[5829 2951]
 [1771 9391]]
Support Vector Machine Accuracy Score = 0.7990980258679374
[0 0 0 ... 1 1 1]
Saved output to file.


Benchmark Classification algorithms for Model Selection
Model Selection is usefull in knowing which Model is Predicting the best results. As we have a number of different types of classification algorithms used in Machine Learning. We are using sklearn library to import all the methods of classification algorithms. We will be using--NaiveBayesClassifier, Support Vector Machine model and Logistic Regression Algorithm

In [15]:
table.head()

Tweet  Label  LR_Prediction  NB_Prediction  \
0                         omg already o      1              0              0   
1               think mi bf cheating tt      0              0              0   
2                   just worry too much      0              1              1   
3      juuuuuuuuuuuuuuuuussssst chillin      1              1              1   
4  sunny again work tomorrow tv tonight      0              0              0   

   SGD_Prediction  
0               0  
1               0  
2               1  
3               1  
4               0